# Generated by Django 3.2.13 on 2022-05-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('artistName', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('releaseDate', models.DateField()),
                ('kind', models.CharField(max_length=30)),
                ('artistId', models.CharField(max_length=12)),
                ('artistUrl', models.CharField(max_length=100)),
                ('contentAdvisoryRating', models.CharField(max_length=30)),
                ('artworkUrl100', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
